### ISSUE TITLE
Auto-launch the browser on `npm start`

### ISSUE THREAD

**Issue by dmethvin-gov** [usds/us-forms-system-starter-app#10]
Just need to add the `--open` option, most likely will land as part of the fix to #5. Simplifies the docs as well, pinging in @bernars-usa since she wanted to document this.

**Comment by bernars-usa** [comment]
Reopening to account for the docs update.

**Comment by bernars-usa** [comment]
Actually, the docs are pretty generic. I'll leave them as-is.
