### ISSUE TITLE
Add CI job

### ISSUE THREAD

**Issue by dmethvin-gov** [usds/us-forms-system-starter-app#23]
Now that we are on the verge of having tests, we can have a CI job!

**Comment by annekainicUSDS** [comment]
I'd love to take on this ticket, but I know Dave has already created a CircleCI account for the USFS, so I'm not sure if I should do the same, or if we should transfer our CircleCI account to a general USDS one? @dmethvin-gov

**Comment by dmethvin-gov** [comment]
I honestly don't think I did anything special for the initial permissions for USFS, if I had to do anything at all. I recall talking to @nacingov about using CircleCI, maybe all the `github.com/usds/*` projects have it enabled automatically?

As far as getting a CircleCI account, you just go to circleci.com and sign up (I did it using the Github signup button). While I was there I set it up so I could run CircleCI on my own fork of the projects which lets me get a CI run before making a pull request to the usds upstream. You may want to do the same, especially while you're experimenting and trying to get everything set up right. It took me a few pushes to my local branches before it all worked.

The only other trick is getting the token, which is now described as part of the build instructions in the USFS wiki. I think I already sent the password along for usfs-publisher.

**Comment by annekainicUSDS** [comment]
Got it, thanks!

**Comment by annekainicUSDS** [comment]
Looking at this some more, do we need the token? I thought that was just for publishing to npm, which we don't need to do for the starter app, correct? Also I don't see the instructions in the wiki for getting the token.

**Comment by dmethvin-gov** [comment]
Yes! So we don’t need a token, at least for now.

Sent from my iPhone

On Sep 27, 2018, at 1:21 PM, Anne Kainic <notifications@github.com<mailto:notifications@github.com>> wrote:


Looking at this some more, do we need the token? I thought that was just for publishing to npm, which we don't need to do for the starter app, correct? Also I don't see the instructions in the wiki for getting the token.

**Comment by dmethvin-gov** [comment]
The CircleCI setup page is [here](https://github.com/usds/us-forms-system/wiki/CircleCI-configuration-for-test-and-deployment), it's not in the right-side ToC, just referenced from the [Release Process](https://github.com/usds/us-forms-system/wiki/Release-Process) page.
