### ISSUE TITLE
React is missing as a dependency

### ISSUE THREAD

**Issue by dmethvin-gov** [usds/us-forms-system-starter-app#3]
I was trying to pull in the latest us-forms-system updates but it looks like dependencies were shuffled in the last few commits of us-forms-system and React no longer shows up after `npm install`. Is this an expected problem, or would you like me to look into it?  It looks to me like some peerDependencies including React are missing from this project. I was able to fix it by adding these as dependencies to the starter app:

```js
  "dependencies": {
    "@department-of-veterans-affairs/formation": "^0.8.0",
    "react": "^15.5.4",
    "react-dom": "^15.6.2",
    "uswds": "^1.6.3",
    "vets-json-schema": "*",
    "us-forms-system": "git+https://github.com/usds/us-forms-system.git#8f37e385097913b49770e61a171562addee53d9d"
  }
```

**Comment by annekainicUSDS** [comment]
Yes I will fix that shortly, thanks @dmethvin-gov!

**Comment by annekainicUSDS** [comment]
Closed with this PR: https://github.com/usds/us-forms-system-starter-app/pull/4.
