### ISSUE TITLE
Error messages aren't being displayed properly

### ISSUE THREAD

**Issue by annekainicUSDS** [usds/us-forms-system-starter-app#9]
Right now when running the starter app, all fields are showing the following error message for invalid fields: "Error Please provide a response".

<img width="509" alt="screen shot 2018-06-30 at 6 18 17 pm" src="https://user-images.githubusercontent.com/25183456/42129425-03b52aec-7c92-11e8-8249-594acbe3cd2e.png">

Questions to answer:
1. Why is "Error" being added to the beginning of each message
2. Why is the specific error message in `validations.js` for each field not being used?

**Comment by dmethvin-gov** [comment]
Fixed by https://github.com/usds/us-forms-system/pull/136, updated for this repo in #13
